UniversityManager/Models/Result.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityManager.Models
{
    public class Result
    {
        [Key]
        public int ResultID { get; set; }

        //Subject Name
        [Required(ErrorMessage = "Subject name is required")]
        public int SubjectID { get; set; }

        //Student Name
        [Required(ErrorMessage = "Student name is required")]
        public int StudentID { get; set; }

        //Speciality
        [Required(ErrorMessage = "Speciality name is required")]
        public int SpecID { get; set; }

        [Required(ErrorMessage = "Course name is required")]
        [Range(1, 4, ErrorMessage = "Course number must be between 1 and 4")]
        public int Course { get; set; }

        [Required(ErrorMessage = "Faculty number is required")]
        [Display(Name = "Faculty Number")]
        public int FacultyNumber { get; set; }

        [Range(2, 6, ErrorMessage = "Grade must be between 2 and 6")]
        public int? Grade { get; set; }

        public virtual Student student { get; set; }
        public virtual Subject subject { get; set; }

    }
}

UniversityManager/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UniversityManager.Models;

namespace UniversityManager.Controllers
{
    public class ResultController : Controller
    {
        private UniversityContext db = new UniversityContext();

        public ActionResult Search(string SearchBox)
        {
            var results = (from t in db.Results
                            where
                                t.subject.SubjectName.Contains(SearchBox)
                                || t.student.StudentName.Contains(SearchBox)
                                || t.subject.Speciality.Contains(SearchBox)
                           select t).ToList();
            return View("Index", results);
        }

        // GET: Result
        public ActionResult Index()
        {
            return View(db.Results.ToList());
        }

        // GET: Result/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Result result = db.Results.Find(id);
            if (result == null)
            {
                return HttpNotFound();
            }
            return View(result);
        }

        // GET: Result/Create
        public ActionResult Create()
        {
            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName");
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentName");
            ViewBag.SpecID = new SelectList(db.Subjects, "SpecID", "Speciality");
            return View();
        }

        // POST: Result/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ResultID,StudentID,SubjectID,SpecID,Course,FacultyNumber,Grade")] Result result)
        {
            if (ModelState.IsValid)
            {
                db.Results.Add(result);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", result.SubjectID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentName", result.StudentID);
            ViewBag.SpecID = new SelectList(db.Subjects, "SpecID", "Speciality", result.SpecID);
            return View(result);
        }

        // GET: Result/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Result result = db.Results.Find(id);
            if (result == null)
            {
                return HttpNotFound();
            }

            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", result.SubjectID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentName", result.StudentID);
            ViewBag.SpecID = new SelectList(db.Subjects, "SpecID", "Speciality", result.SpecID);
            return View(result);
        }

        // POST: Result/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ResultID,StudentID,SubjectID,SpecID,Course,FacultyNumber,Grade")] Result result)
        {
            if (ModelState.IsValid)
            {
                db.Entry(result).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SubjectID = new SelectList(db.Subjects, "SubjectID", "SubjectName", result.SubjectID);
            ViewBag.StudentID = new SelectList(db.Students, "StudentID", "StudentName", result.StudentID);
            ViewBag.SpecID = new SelectList(db.Subjects, "SpecID", "Speciality", result.SpecID);
            return View(result);
        }

        // GET: Result/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Result result = db.Results.Find(id);
            if (result == null)
            {
                return HttpNotFound();
            }
            return View(result);
        }

        // POST: Result/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Result result = db.Results.Find(id);
            db.Results.Remove(result);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UniversityManager/Views/Result/Create.cshtml
@model UniversityManager.Models.Result

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Result</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SubjectID, "Subject", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectID", ViewBag.SubjectID as SelectList, "Select Subject", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, "Student", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentID", ViewBag.StudentID as SelectList, "Select Student", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpecID, "Speciality", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SpecID", ViewBag.SpecID as SelectList, "Select Speciality", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SpecID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacultyNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacultyNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacultyNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

UniversityManager/Views/Result/Delete.cshtml
@model UniversityManager.Models.Result

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Result</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.subject.SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.subject.SubjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.student.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.student.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.subject.Speciality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.subject.Speciality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacultyNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacultyNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UniversityManager/Views/Result/Details.cshtml
@model UniversityManager.Models.Result

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Result</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.subject.SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.subject.SubjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.student.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.student.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.subject.Speciality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.subject.Speciality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course)
        </dd>

            @if (User.IsInRole("Admin"))
            {
        <dt>
            @Html.DisplayNameFor(model => model.FacultyNumber)
        </dt>
            }

            @if (User.IsInRole("Admin"))
            {
        <dd>
            @Html.DisplayFor(model => model.FacultyNumber)
        </dd>
            }

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

    </dl>
</div>

@if (User.IsInRole("Admin"))
{
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ResultID }) |
    @Html.ActionLink("Back to List", "Index")
</p>
}

@if (User.IsInRole("Student"))
{
<p>
    @Html.ActionLink("Back to List", "Index")
</p>
}

UniversityManager/Views/Result/Edit.cshtml
@model UniversityManager.Models.Result

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Result</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ResultID)

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectID, "Subject", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectID", ViewBag.SubjectID as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, "Student", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentID", ViewBag.StudentID as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpecID, "Speciality", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SpecID", ViewBag.SpecID as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SpecID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FacultyNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FacultyNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FacultyNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

UniversityManager/Views/Result/Index.cshtml
@model IEnumerable<UniversityManager.Models.Result>

@{
    ViewBag.Title = "Index";
}

<h2>Exam Results</h2>

<div class="form-control-static">
    @using (Html.BeginForm("Search", "Result"))
    {
        <div class="form-group col-xs-6 col-md-push-0">
            @Html.Editor("SearchBox", new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group col-xs-6 col-md-pull-3">
            <input class="btn btn-default" type="submit" value="Search" />
        </div>
    }
</div>

@if (User.IsInRole("Admin"))
{
<p>
    @Html.ActionLink("Create New", "Create")
</p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.subject.SubjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.student.StudentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.subject.Speciality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course)
        </th>
        @if (User.IsInRole("Admin"))
        {
        <th>
            @Html.DisplayNameFor(model => model.FacultyNumber)
        </th>
        }
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.subject.SubjectName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.student.StudentName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.subject.Speciality)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course)
        </td>
        @if (User.IsInRole("Admin"))
        {
         <td>
            @Html.DisplayFor(model => item.FacultyNumber)
         </td>
        }
         <td>
            @Html.DisplayFor(model => item.Grade)
         </td>
            @if (User.IsInRole("Admin"))
             {
         <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ResultID }) |
            @Html.ActionLink("Details", "Details", new { id = item.ResultID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ResultID })
         </td>
              }
            @if (User.IsInRole("Student"))
              {
         <td>
            @Html.ActionLink("Details", "Details", new { id = item.ResultID })
         </td>
              }
    </tr>
}
</table>